### ISSUE TITLE
Bot does not forward messages - whin-receive doesn't work, even if it's on "listening to whatsapp" state.

### ISSUE THREAD

**Issue by S1BO-GER** [inUtil-info/node-red-contrib-whin#41]
Hello,

I turned on the "new" "self-deleting messages" feature in Whatsapp.

I immediately noticed that I can still receive messages, but I can't send messages to win-recieve in Node-Red.

The messages have two grey chops (normal condition).

After noticing this, I disabled the new feature, but unfortunately my messages are still not getting through to Node-Red.

Also the signup message does not work.

Is there a known fix for that?

Greetings,
Tobias Speiser

**Comment by lu4t** [comment]
which is the response you are getting when you send a "signup" message?

**Comment by S1BO-GER** [comment]
I do not get a respons.
After the signup Message, nothing happens.

**Comment by lu4t** [comment]
ok. Let us have a look.... probably this is related with turning on the "new" "self-deleting messages" feature in Whatsapp.

**Comment by S1BO-GER** [comment]
Do you need any informations from me? (Ending from tel. Number or token)

**Comment by lu4t** [comment]
> Do you need any informations from me? (Ending from tel. Number or token)

no, it's okay. 
If signup msg gets no response, it must be there's something going on on the whatsapp side. You don't need to send us anything, we will activate the feature on whatsapp and test.

**Comment by S1BO-GER** [comment]
Hello,
I have good news.
I deleted my auth in node-red (with the number and token), then I wrote the bot signup again and it reported back with my token. Then I configured auth in node-red again and now it works.
I can send and receive messages in node-red.

But thanks for the help and the quick answers.

**Comment by S1BO-GER** [comment]
Update: After a received and sent message, it stopped working.

**Comment by lu4t** [comment]
> Hello, I have good news. I deleted my auth in node-red (with the number and token), then I wrote the bot signup again and it reported back with my token. Then I configured auth in node-red again and now it works. I can send and receive messages in node-red.
> 
> But thanks for the help and the quick answers.

that's weird... the backend should send a token everytime you request it. It makes no sense that it starts working just by deleting the auth on the local config.

I leave this open cause there must be something else going on...

**Comment by lu4t** [comment]
see #42

**Comment by S1BO-GER** [comment]
Hello,
what ist the ephemeralSetting  in Case #42 ?

Is it the setting what i call "self-deleting messages"?

**Comment by lu4t** [comment]
> Hello, what ist the ephemeralSetting in Case #42 ?
> 
> Is it the setting what i call "self-deleting messages"?

yes, it is. Your issue should be solved. Check it, pls

**Comment by S1BO-GER** [comment]
It's fixed, that I recive always the signup token.

But my messages from the mobile to node red still don't work.

**Comment by lu4t** [comment]
I would:
1. make sure the receiver node has the right config (phone and token).
2. restart node-red.
3. you should see the "connected to whatsapp" green message.

If you don't see it green, there must be an error msg on the log. If so, copy and paste it here.

**Comment by S1BO-GER** [comment]
1. I have checked it 3 times, everything is fine. Sending messages to my phone works.
2. Restarted it twice. Still the same problem.
3. It's green and "connected to whatsapp".

It works with my friend's phone and her number + token, but not with mine.

**Comment by lu4t** [comment]
Need some more info to understand what's going on. Are the two listeners running on the same node-red instance?

**Comment by S1BO-GER** [comment]
Yes, both listeners are runing on the same node-red instance in the same flow.
2 different phones, with two different tokens and numbers.

Both worked fine. Then I activated the new function. After that, I no longer received a token when I wrote "signup" (now fixed), and I could only receive messages from my node-red instance. Sending messages to my node-red instance no longer works.
Messages from my girlfriend's phone (her number + token) works all the time.

My and her listener is green. I checkt the token + number a few times, recreated the profile in the listener, nothing changed. I can still only revieve, but sending from my phone to my node-red instance isn' t working.

**Comment by lu4t** [comment]
I believe the WhatsApp listener node (whin-receive) will not be able to work on the same nodered runtime with 2 different numbers at the same time. You will only be able to push msgs with different numbers, not receiving. The Nw protocols used for send and receive are different.
Try to run each receive nodes on different nodered runtimes.

**Comment by S1BO-GER** [comment]
I have set up a new node-red instance on a debian vm.
It still doesn't work, I can only send messages to my number but not back.

There must be something in the back end with my number or token. must be wrong.

Here is a screenshot. Sending to the phone works, but not back. Completely new instance, deleted everything in the old instance.
![image](https://user-images.githubusercontent.com/112906292/189486822-156a300d-9c5b-4381-ba7c-a0380c6a1b22.png)

**Comment by lu4t** [comment]
I have increased the resources of the back-end; we have a lot of open sessions, and that might be the root cause that was affecting you. There's nothing wrong with your token / phone, and the backend server has no errors.
Please, restart node-red and try again, that's all I can tell you.

**Comment by S1BO-GER** [comment]
Sadly it's still not working. But i will get a new number in a few month, than it should work again.
Thanks for your help.

**Comment by S1BO-GER** [comment]
Hello,

new phone with new number arrived and everything works fine.
(Two numbers with two tokens in one node-red flow is possible.)

I don't know why it doesn't work after I turned the delete message function on and off....

You can close the case again if you want.

**Comment by Yakwrangler** [comment]
Also made mistake of using WA self-deleting message option ... followed above procedures, with same outcome of receive only from NR.

FWIW - restored normal operation by deleting chat content with 'Clear chat', followed by deleting Chat itself. 

Sent a new message from NR towards phone to restore a Chat & all has worked fine ever since ... YMMV

**Comment by S1BO-GER** [comment]
Thank you for the solution.

**Comment by lu4t** [comment]
thanks @Yakwrangler for the suggested solution :)
